#!/usr/bin/env bash

tmpDir="$(mktemp -d /tmp/cl-archive.XXXXXXXX)"

case "$1" in
    *.tar.gz | *.tgz) tar xzf "$1" -C "$tmpDir" ;;
    *.tar.xz) tar xJf "$1" -C "$tmpDIr" ;;
    *.zip) unzip "$1" -d "$tmpDir" ;;
    *) cp -r --no-preserve=mode,ownership "$1"/* "$tmpDir"/ ;;
esac

echo -n "$tmpDir"
