#!/usr/bin/env bash

tmpDir="$(mktemp -d /tmp/cl-archive.XXXXXXXX)"

case "$1" in
    *.tar.gz | *.tgz) tar xzf "$1" -C "$tmpDir" ;;
    *.tar.xz) tar xJf "$1" -C "$tmpDIr" ;;
    *.zip) unzip "$1" -d "$tmpDir" ;;
    *)
        echo -n "$1"
        exit
        ;;
esac

echo -n "$tmpDir"
